LP03 158 | Criar componente de destaque adoção
UniPatas/UniPatas pull request #21
Opened 2023-11-23 03:52 UTC by pedroutopia

Solid Shapes com as imagens dos animais do feed adote.

 Trello: https://trello.com/c/3Rs2r1Xd

2023-11-23 21:36 UTC, thidspessoa requested changes

2023-11-23 21:36 UTC, thidspessoa commented on src/app/page.jsx
**Iniciada 1 rodada de testes**

2023-11-23 21:36 UTC, thidspessoa commented on src/components/DestaqueAdocao.jsx
Adicione a propiedade `alt` a suas tags `img`, por favor. É um requisito para termos mais acessibilidade em nossa plataforma. 

![image](https://github.com/UniPatas/UniPatas/assets/104585635/aca7e928-d09e-406a-996b-0ee3b613414f)

2023-11-23 21:36 UTC, thidspessoa commented on src/app/page.jsx
Olá peu, seu código falhou em um dos requisitos dos _Testes de padronização e convenção do código_, sendo ele:
![image](https://github.com/UniPatas/UniPatas/assets/104585635/520ab9ce-b507-45a1-a7e1-dcf1de67544a)

**Por favor, se atente a isso. Comentários são essenciais para um código de qualidade e escalavel. Corriga e solicite novamente a revisão.**

2023-11-23 21:36 UTC, thidspessoa commented on src/app/page.jsx
Olá peu, seu código falhou em um dos requisitos dos: _Testes de padronização e convenção do código_, sendo ele:

![image](https://github.com/UniPatas/UniPatas/assets/104585635/57deab87-d2fe-477b-8ecf-0173ff4e75cb)

**Por favor, corriga isso e solicite novamente a revisão.**

2023-11-23 21:36 UTC, thidspessoa commented on src/app/page.jsx
Peu, peço que faça uma pequena correção em seu código. Ele falhou em um dos casos de teste que deveria estar passando, no caso, o fluid shape do meio deveria redirecionar a tela de adote, sem nenhum filtro aplicado (Já que o filtro de cachorro e gato, é o estado padrão da página.).

![image](https://github.com/UniPatas/UniPatas/assets/104585635/19d7ec8e-bc21-461f-9355-5273932a1ff4)
![image](https://github.com/UniPatas/UniPatas/assets/104585635/cb607805-3c46-4b8c-9a48-67e38935eaaa)


**Por favor, faça as devidas alterações e solicite novamente revisão.**

2023-11-23 21:41 UTC, thidspessoa commented
**1 rodada de testes FINALIZADA**

**RESULTADO: **_Aguardando alterações._

### CTs Falhados e Aprovados

- **FALHADOS:** 3
- **APROVADOS:** 0

- **Testes de padronização e convenção do código:** 3 falharam, 5 aprovaram.

### Rotina de testes realizada

[Clique-me](https://malachite-anaconda-31c.notion.site/LP03-158-917f2e6a3c45428683438339ddf88a0b?pvs=4)

2023-11-24 01:57 UTC, pedroutopia commented on src/components/DestaqueAdocao.jsx
Feito

2023-11-24 01:57 UTC, pedroutopia commented
Iniciando mudanças.

2023-11-24 01:57 UTC, pedroutopia commented on src/app/page.jsx
Feito.

2023-11-24 01:57 UTC, pedroutopia commented on src/app/page.jsx
Feito!

2023-11-24 02:02 UTC, pedroutopia commented
Foi adicionado o "alt" nas imagens, as rotas para a pagina adote e alguns comentários para uma melhor visualização do código.

2023-11-26 17:59 UTC, thidspessoa approved these changes

2023-11-26 17:59 UTC, thidspessoa commented on src/app/page.jsx
**Iniciada 2 rodada de testes**

2023-11-26 17:59 UTC, thidspessoa commented on src/app/page.jsx
**2 rodada de testes FINALIZADA**

**RESULTADO:** _Aprovado, pronto para mergiar._

### CTs Falhados e Aprovados

- **FALHADOS:** 2
- **APROVADOS:** 1

- **Testes de padronização e convenção do código:** Todos aprovados.

### Rotina de testes realizada

[Clique-me](https://malachite-anaconda-31c.notion.site/LP03-158-917f2e6a3c45428683438339ddf88a0b?pvs=4)

2023-11-26 18:00 UTC, merged