LP03 249 | Componente de anuncio (Container de anúncio do patrocinador) - home page
UniPatas/UniPatas pull request #22
Opened 2023-11-23 15:34 UTC by pedroutopia

Componente de anúncio dos nossos parceiros.

Trello: https://trello.com/c/xnGvtkC9

2023-11-23 22:24 UTC, thidspessoa requested changes

2023-11-23 22:24 UTC, thidspessoa commented on src/components/Home/ContainerAnuncio.jsx
Olá, peu. Percebi que seu código falhou em um dos requisitos do _Teste de padronização e convenção do código_, no caso o:
![image](https://github.com/UniPatas/UniPatas/assets/104585635/acb395e0-f776-4756-a04c-33837eb6c4a3)

Porém, analisando a complexidade do seu código, não se faz necessário uma alteração somente para isso, já que ele não possui uma arquitetura muito complexa. 
**Mas fica como notificação para se atentar de uma proxima vez, comentários são essenciais para manter um código organizado e escalavel.**

2023-11-23 22:24 UTC, thidspessoa commented on src/app/adote/layout.jsx
**Iniciada 1 rodada de testes**

2023-11-23 22:24 UTC, thidspessoa commented on src/components/Home/ContainerAnuncio.jsx
Olá, peu. Infelizmente seu código reprovou em um dos requisitos do _Teste de padronização e convenção do código_, no caso o:

![image](https://github.com/UniPatas/UniPatas/assets/104585635/1b4a21c5-9b6e-47c5-8b84-4902ab001943)

Você deve inserir seu componente dentro da pasta `Home` já existente em `components`
**Por favor, corrija e solicite novamente a revisão.**

2023-11-23 22:24 UTC, thidspessoa commented on src/components/Home/ContainerAnuncio.jsx
**1 rodada de testes FINALIZADA**
**RESULTADO:** _Aguardando 1 alteração._

### CTs Falhados e Aprovados

- **FALHADOS:** 1
- **APROVADOS:** 2
> Total: 3 CTS

- **Testes de padronização e convenção do código:** _7 aprovados, 1 reprovado._

### Rotina de testes realizada

[Clique-me](https://malachite-anaconda-31c.notion.site/LP03-249-d37c184e216f492187486557749430f9?pvs=4)

2023-11-24 02:13 UTC, pedroutopia commented on src/components/Home/ContainerAnuncio.jsx
Feito.

2023-11-24 02:13 UTC, pedroutopia commented on src/components/Home/ContainerAnuncio.jsx
Acredito que houve um equívoco, nesse caso, o componente já se encontra na pasta HOME, igualmente a NavBar e o Footer.

2023-11-24 02:13 UTC, pedroutopia commented
Iniciando mudanças.

2023-11-24 02:15 UTC, pedroutopia commented
Foi adicionado uma descirção no código para ajudar a diferenciar sobre o que se trata.

2023-11-27 19:29 UTC, Melferss commented
Revisão iniciada

2023-11-28 18:47 UTC, Melferss commented
Revisão iniciada.

2023-11-28 18:49 UTC, Melferss approved these changes, later dismissed

2023-11-28 18:55 UTC, Melferss commented
Revisão finalizada.

2023-11-28 23:47 UTC, thidspessoa approved these changes, later dismissed

2023-11-29 13:43 UTC, merged