LP03-250 | Componente de destaque de notícias (Forum)
UniPatas/UniPatas pull request #23
Opened 2023-11-23 15:41 UTC by pedroutopia

Componente que mostrará as últimas publicações feitas do fórum na home.

Trello: https://trello.com/c/hprkohLP

2023-11-23 22:58 UTC, thidspessoa requested changes

2023-11-23 22:58 UTC, thidspessoa commented on src/app/page.jsx
**Iniciada 1 rodada de testes**

2023-11-23 22:58 UTC, thidspessoa commented on src/app/page.jsx
Olá, peu. Percebi que seu códgio acabou falhando em um dos requisitos do _Teste de padronização e convenção do código_, mais especificamente no requisito:

![image](https://github.com/UniPatas/UniPatas/assets/104585635/1a1415ed-7ff1-42ca-92f9-764c3344f3bb)

Você deve inserir o seu componente dentro da pasta `Home` já existente no diretorio `components`.
**Por favor, corrija e solicite novamente a revisão!**

2023-11-23 22:58 UTC, thidspessoa commented on src/app/page.jsx
Olá, peu. Percebi que seu códgio acabou falhando em um dos requisitos do Teste de padronização e convenção do código, mais especificamente no requisito:

![image](https://github.com/UniPatas/UniPatas/assets/104585635/3ddba2ca-7b49-4728-bb21-d1eed30d28ac)

Os comentários são essenciais para um código escalavel e legivel. 
Por favor, corrija e solicite novamente a revisão!

2023-11-23 22:58 UTC, thidspessoa commented on src/app/page.jsx
**1 rodada de testes FINALIZADA**

**RESULTADO:** _Aguardando 2 alterações_

### CTs falhados e aprovados

- **APROVADOS:** 1
- **REPROVADOS:** 2
> Total: 3 CTs

- **Testes de padronização e convenção do código:** _6 aprovados, falhou em 2._

### Rotina de testes realizada

[Clique-me](https://malachite-anaconda-31c.notion.site/LP03-250-8e4d46ad3b104886a97fa4daa88d7686?pvs=4)

2023-11-24 02:23 UTC, pedroutopia commented on src/app/page.jsx
Acredito que houve um equívoco, nesse caso, o componente já se encontra na pasta HOME, igualmente a NavBar e o Footer.

2023-11-24 02:23 UTC, pedroutopia commented on src/app/page.jsx
Feito.

2023-11-24 02:23 UTC, pedroutopia commented
Iniciando mudanças.

2023-11-28 18:53 UTC, Melferss approved these changes

2023-11-28 18:53 UTC, Melferss commented
Revisão iniciada.

2023-11-28 18:56 UTC, Melferss commented
Revisão finalizada.

2023-11-28 23:47 UTC, thidspessoa approved these changes

2023-11-28 23:53 UTC, merged