LP03-157
UniPatas/UniPatas pull request #3
Opened 2023-11-03 13:03 UTC by pedroutopia

Componente de NavBar.
Será responsável por realizar toda a navegação do nosso site, possúi a barra de pesquisa e também a opção de fazer login na nossa plataforma.

2023-11-03 21:30 UTC, pedroutopia commented
https://trello.com/c/1W3omIea

2023-11-05 18:05 UTC, thidspessoa reviewed
Peu uma coisa interessante para poluir menos o código, deixar mais organizado e de fácil leitura é utilizar as tags de encapsulamento do HTML como:
`Head, Section ` Separando por uma especie de arvore e ramificações, cada tag dessa do html tem sua função.

2023-11-05 18:15 UTC, thidspessoa commented on src/components/ComponenteNavBar.js
> +    <div>
Para se iniciar um componente, dentro da função o jsx precisa estar dentro de um elemento pai. Nesse caso você fez corretamente utilizando uma `<div>` tag para encapsular todo o seu JSX. Mas esse metodo pode vir a poluir o HTML da pagina, existe uma forma mais moderna e que é uma boa pratica, utilizando somente uma tag vazia `<> </>` para encapsular seu código.

2023-11-05 18:41 UTC, thidspessoa requested changes
Adicione uma classe para esconder ` <div>UniPatas Repository</div>` tag, em **page.js** dentro da pasta app.

2023-11-05 18:44 UTC, thidspessoa requested changes
Remova a classe `border` da tag     `<div>UniPatas Repository</div>` na linha 9 de **ComponenteNavBar.js**

2023-11-05 18:44 UTC, thidspessoa commented on src/components/ComponenteNavBar.js
> +        <div className="w-full max-w-[1246px] mx-auto border border-red-900">
Remova a classe border.

2023-11-05 18:46 UTC, thidspessoa requested changes

2023-11-05 18:46 UTC, thidspessoa commented on src/components/ComponenteNavBar.js
> +                <a href="#">
Adicionar no href o link para a página home, para que ao clicar redirecione para a mesma.

2023-11-05 18:48 UTC, thidspessoa requested changes
Crie uma pasta `Home` dentro de `components` e insira o seu componente dentro dela.

2023-11-05 18:59 UTC, thidspessoa requested changes

2023-11-05 18:59 UTC, thidspessoa commented on src/components/ComponenteNavBar.js
> +                <a
altere o título de `ADOTE` para `AJUDA`

2023-11-05 19:05 UTC, thidspessoa commented
Revisão finalizada, aguardando alterações.
Rotina de testes:
https://www.notion.so/LP03-157-4d582191aaa949129926335a3dfeb54c?pvs=4

2023-11-06 14:34 UTC, thidspessoa commented
2 Rodada de testes iniciada

2023-11-06 14:49 UTC, thidspessoa requested changes

2023-11-06 14:49 UTC, thidspessoa commented on src/components/NavBar.jsx
> +                  <a href="http://localhost:3000">
Erro inesperado ao clicar na logo da plataforma.
![image](https://github.com/UniPatas/UniPatas/assets/104585635/a7db5344-ab58-4f16-9ab8-14cada69ad03)

2023-11-06 14:53 UTC, thidspessoa requested changes

2023-11-06 14:53 UTC, thidspessoa commented on src/components/ComponenteNavBar.js
Crie uma pasta chamada `pagHome` dentro da pasta `components` e insira o arquivo **NavBar.jsx** dentro da pasta Home, não precisa criar uma pasta especifica para o componente, já que ele é apenas um unico arquivo e não tem relacionados. Seria interessante criar uma pasta especifica para o componente dentro da pasta `pagHome` caso ele tivesse algum outro arquivo secundário como um script, relacionado a ele, e que precisasse ficar junto.

2023-11-06 14:58 UTC, thidspessoa requested changes

2023-11-06 14:58 UTC, thidspessoa commented on src/components/NavBar.jsx
> +                <div className=" pt-[5px]">
Altere o título de `ADOTE` para `AJUDA`. Você fez, mas fez no ADOTE errado, no caso é o ADOTE antes de login, veja como está no prototipo e na propia documentação:
![image](https://github.com/UniPatas/UniPatas/assets/104585635/49a6c12c-547f-4478-bc52-7f70395892f8)
https://senacpernambuco-my.sharepoint.com/:w:/g/personal/thiago46501036_edu_pe_senac_br/EX7K43XP9h1PtLzNn1CV5isBLxkKYtoA3a8zy4JyXEkFxg?e=YlshkQ

2023-11-06 15:00 UTC, thidspessoa commented
2 rodadas de testes finalizadas, aguardando a resolução do **LG01**
**Rotina de testes:**
 https://www.notion.so/LP03-157-4d582191aaa949129926335a3dfeb54c

2023-11-06 17:06 UTC, pedroutopia commented on src/components/NavBar.jsx
> +                <div className=" pt-[5px]">
ai misericordia, é tanta coisa na minha cabeça q eu tô elouquecendo kkkkkkkkkk
vou ajeitar

2023-11-08 19:20 UTC, closed without merging