LP03-235
UniPatas/UniPatas pull request #4
Opened 2023-11-03 13:27 UTC by pedroutopia

Componente Footer da plataforma, será usado em todas as telas.
No componente, existem 3 seções, a primeira é sobre a UniPatas, a segunda é uma seção com opções de contato etc, a última seção é das redes sociais da UniPatas.

2023-11-03 21:30 UTC, pedroutopia commented
https://trello.com/c/Xb1QbfBS

2023-11-05 21:15 UTC, thidspessoa commented
Iniciada revisão

2023-11-05 21:44 UTC, thidspessoa reviewed
Adicionar componente `ComponenteFooter` em uma pasta chamada `Home` dentro da pasta `components`

2023-11-05 21:48 UTC, thidspessoa requested changes

2023-11-05 21:48 UTC, thidspessoa commented on src/components/ComponenteFooter.js
Adicionar componente `ComponenteFooter` em uma pasta chamada `Home` dentro da pasta `components`

2023-11-05 21:49 UTC, thidspessoa commented on src/components/ComponenteFooter.js
Uma sugestão e boa prática é sempre adicionar comentários pontuais no seu código, para poder ficar mais fácil a leitura e guiação dentro do mesmo.

2023-11-05 23:11 UTC, thidspessoa requested changes

2023-11-05 23:11 UTC, thidspessoa commented on src/components/ComponenteFooter.js
![image](https://github.com/UniPatas/UniPatas/assets/104585635/93a03386-c2c1-4a61-9008-1f774ce640d0)
Correção no link do facebook, está dando conteudo invalido

2023-11-05 23:11 UTC, thidspessoa commented on src/components/ComponenteFooter.js
Alterar ícone do Twitter para o ícone do TikTok, pois é para onde é redirecionado ao clicar.
![image](https://github.com/UniPatas/UniPatas/assets/104585635/1ff1572a-8afc-4db4-87e7-fa0393d6f88c)

2023-11-05 23:12 UTC, thidspessoa commented
Revisão finalizada, aguardando alterações.
**Rotina de testes:** https://www.notion.so/87bff33b4b7a42c787641331798371dd?v=faaa4064632e469d929e5f371acba9f3&p=aa7e046078a04a7685d7bafa7be87fa3&pm=s

2023-11-06 12:48 UTC, pedroutopia commented on src/components/ComponenteFooter.js
Essa questão é no próprio facebook, acho que é devido a inatívidade da conta. Ignora essa parte por enquanto, mais futuramente a gente resolve ela. Podemos até remover o ícone do face futuramente, caso necessário.

2023-11-06 14:19 UTC, thidspessoa commented
2 rodada de testes iniciada

2023-11-06 14:26 UTC, thidspessoa requested changes

2023-11-06 14:26 UTC, thidspessoa commented on src/components/pagHome/Footer/Footer.jsx
> +                  <a href="http://localhost:3000/">
Erro ao clicar na logo da plataforma, ela retorna o erro abaixo. 
![image](https://github.com/UniPatas/UniPatas/assets/104585635/61ea11fd-b32f-437b-9042-da5e356b273b)

2023-11-06 14:32 UTC, thidspessoa commented
Rodada de testes 2 finalizada.
**Rotina de testes: **
https://malachite-anaconda-31c.notion.site/LP03-235-aa7e046078a04a7685d7bafa7be87fa3?pvs=4

2023-11-16 16:46 UTC, thidspessoa requested changes

2023-11-16 16:46 UTC, thidspessoa commented on src/components/Home/Footer.jsx
![image](https://github.com/UniPatas/UniPatas/assets/104585635/706c7761-fbe2-4c72-bf35-e54393df54c0)

Peu, da um espaço entre o footer e os demais elementos. Pode fazer isso usando o `gap` do flexBox

2023-11-17 09:32 UTC, thidspessoa approved these changes

2023-11-17 09:32 UTC, thidspessoa commented on src/components/Home/Footer.jsx
**Iniciada 3 rodada de testes**

2023-11-17 09:32 UTC, thidspessoa commented on src/components/Home/Footer.jsx
### 3 Rodada de testes Finalizada
#4 
**Resultado:** Aprovado

### CTs aprovados e Falhados

- **Aprovados:** 7
- **Reprovados:** 2

### Rotina de testes realizada

[Click-me](https://malachite-anaconda-31c.notion.site/LP03-235-aa7e046078a04a7685d7bafa7be87fa3?pvs=4)

2023-11-17 09:32 UTC, merged